name: tr_shop
description: A Assessment For TransMedia Inc.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  #State Management
  get: ^4.6.6

  #UI
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^16.3.2
  flutter_launcher_icons: ^0.13.1

  #Network
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  connectivity_plus: ^2.3.8

  #Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any


flutter:

  uses-material-design: true

  assets:
    - assets/
